=== srivastavatilotama1/VaishaliData/MyOwnMPTSolutions/Module1-Set-07-Employee-Referral/92595_Module_1MPT/Section4/Section_4.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">

	
	<!-- Create name type -->
	
	<xs:simpleType name="name">
		<xs:restriction base="xs:string">
			<xs:maxLength value="20"/>
		</xs:restriction>
	</xs:simpleType>
	
	<!-- Create address type -->
	
	<xs:simpleType name="address">
		<xs:restriction base="xs:string">
			<xs:maxLength value="30"/>
		</xs:restriction>
	</xs:simpleType>
	
	<!-- Create degree type -->
	
	<xs:simpleType name="degree">
		<xs:restriction base="xs:string">
			<xs:maxLength value="4"/>
		</xs:restriction>
	</xs:simpleType>
	
	<!-- Create phone type -->
	
	<xs:simpleType name="phone">
		<xs:restriction base="xs:string">
			<xs:pattern value="[7-9][0-9]{9}"/>
		</xs:restriction>
	</xs:simpleType>
	
	<!-- Define ref no. Tag -->
	
		<xs:element name="refno" type="xs:int" />
	
	<!-- Define ref name Tag -->
		
		<xs:element name="refname" type="name"/>
		
	<!-- Define Address Tag -->
		
		<xs:element name="address" type="address"/>
		
	<!-- Define number Tag -->
	
		<xs:element name="phoneno" type="phone"/>
		
	<!-- Define Degree Tag -->
		<xs:element name="degree" type="degree"/>
		
	<!-- Define emp no. Tag -->
	
		<xs:element name="empno" type="xs:int" />
		
	<!-- Define employee Tag -->
		<xs:element name="employee">
			<xs:complexType>
				<xs:sequence>
					<xs:element ref="refno"/>
					<xs:element ref="refname"/>
					<xs:element ref="address"/>
					<xs:element ref="phoneno"/>
					<xs:element ref="degree"/>
					<xs:element ref="empno"/>
				</xs:sequence>
			</xs:complexType>
		</xs:element>
		
	<!-- Define emp Tag -->
	
		<xs:element name="emp" >
			<xs:complexType>
				<xs:sequence>
					<xs:element ref="employee" maxOccurs="unbounded"/>
				</xs:sequence>
			</xs:complexType>
		</xs:element>
</xs:schema>

=== srivastavatilotama1/VaishaliData/MyOwnMPTSolutions/Module1-Set-07-Employee-Referral/92595_Module_1MPT/Section4/Section_4.xml
<?xml version="1.0" encoding="UTF-8"?>
<emp xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Section_4.xsd" >
	
	<employee>
		<refno>5000</refno>
		<refname>Praveen</refname>
		<address>Chennai</address>
		<phoneno>9897969594</phoneno>
		<degree>BE</degree>
		<empno>104</empno>		
	</employee>
	
	<employee>
		<refno>5001</refno>
		<refname>Anbazhagan</refname>
		<address>Bangalore</address>
		<phoneno>8989878767</phoneno>
		<degree>BSc</degree>
		<empno>106</empno>		
	</employee>
	
	<employee>
		<refno>5002</refno>
		<refname>Saravanan</refname>
		<address>Chennai</address>
		<phoneno>7876757878</phoneno>
		<degree>BE</degree>
		<empno>104</empno>		
	</employee>
	
	<employee>
		<refno>5003</refno>
		<refname>Rakesh</refname>
		<address>Pune</address>
		<phoneno>7788778877</phoneno>
		<degree>BSc</degree>
		<empno>105</empno>		
	</employee>
	
	<employee>
		<refno>5004</refno>
		<refname>Vikas</refname>
		<address>Mumbai</address>
		<phoneno>9844577866</phoneno>
		<degree>BE</degree>
		<empno>106</empno>		
	</employee>
	
	<employee>
		<refno>5005</refno>
		<refname>Sandeep</refname>
		<address>Pune</address>
		<phoneno>8867756643</phoneno>
		<degree>BSc</degree>
		<empno>102</empno>		
	</employee>
	
	<employee>
		<refno>5006</refno>
		<refname>Sumit</refname>
		<address>Bangalore</address>
		<phoneno>9897969594</phoneno>
		<degree>BE</degree>
		<empno>106</empno>		
	</employee>
	
	<employee>
		<refno>5007</refno>
		<refname>Rajesh</refname>
		<address>Mumbai</address>
		<phoneno>7654323456</phoneno>
		<degree>BSc</degree>
		<empno>104</empno>		
	</employee>
	
	<employee>
		<refno>5008</refno>
		<refname>Shalini</refname>
		<address>Chennai</address>
		<phoneno>9897969594</phoneno>
		<degree>BE</degree>
		<empno>105</empno>		
	</employee>

</emp>
