=== srivastavatilotama1/VaishaliData/MyOwnMPTSolutions/Module1-Set-10/Users.xsd
<?xml version="1.0" encoding="iso-8859-1" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="Users">
	<xs:complexType>
		<xs:sequence>
			<xs:element name="User" maxOccurs="unbounded">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="Username">
						<xs:simpleType>
						<xs:restriction base="xs:string">
						<xs:pattern value="[A-Z][a-z]+"></xs:pattern>
						</xs:restriction>
						</xs:simpleType>
						</xs:element>
						<xs:element name="Password">
						<xs:simpleType>
						<xs:restriction base="xs:string">
						<xs:pattern value="[a-z]+[@][0-9]+"></xs:pattern>
						</xs:restriction>
						</xs:simpleType>
						</xs:element>
						<xs:element name="Type">
						<xs:simpleType>
						<xs:restriction base="xs:string">
						<xs:enumeration value="seller"></xs:enumeration>
						<xs:enumeration value="customer"></xs:enumeration>
						</xs:restriction>
						</xs:simpleType>
						</xs:element>
						<xs:element name="EmailID">
						<xs:simpleType>
						<xs:restriction base="xs:string">
						<xs:pattern value="[a-z]+[@][a-z]+[.][com]+"></xs:pattern>
						</xs:restriction>
						</xs:simpleType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
</xs:element>
</xs:schema>

=== srivastavatilotama1/VaishaliData/MyOwnMPTSolutions/Module1-Set-10/Users.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Stores User details -->
<Users xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
 xs:noNamespaceSchemaLocation="Users.xsd">
	<User>
		<Username>John</Username>
		<Password>john@123</Password>
		<Type>seller</Type>
		<EmailID>john@igate.com</EmailID>
	</User>
	<User>
		<Username>Fazil</Username>
		<Password>fazil@123</Password>
		<Type>seller</Type>
		<EmailID>fazil@igate.com</EmailID>
	</User>
	<User>
		<Username>Jim</Username>
		<Password>jim@123</Password>
		<Type>customer</Type>
		<EmailID>jim@igate.com</EmailID>
	</User>
	<User>
		<Username>Rose</Username>
		<Password>rose@123</Password>
		<Type>seller</Type>
		<EmailID>rose@igate.com</EmailID>
	</User>
</Users>
