=== srivastavatilotama1/VaishaliData/My IGate Web Basics/My Demo Web Basic/XML-Lect Demo/Examples With XSD/0011-orders/order.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	
	<xs:element name="customername" type="xs:string"/>
	<xs:element name="salesperson" type="xs:string"/>
	<xs:element name="shippingaddress" type="xs:string"/>
	<xs:element name="orderdate" type="xs:string"/>
	
	<xs:element name="order">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="orderid"/>
				<xs:element ref="customername"/>
				<xs:element ref="orderdate"/>
				<xs:element ref="salesperson"/>
				<xs:element ref="shippingaddress"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="orderid">
		<xs:simpleType>
			<xs:restriction base="xs:byte">
				<xs:enumeration value="1"/>
				<xs:enumeration value="2"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	
	<xs:element name="orders">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="order" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== srivastavatilotama1/VaishaliData/My IGate Web Basics/My Demo Web Basic/XML-Lect Demo/Examples With XSD/0011-orders/order.xml
<?xml version="1.0"?>

<orders xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="order.xsd">
	<order>
		
        <orderid>1</orderid>
		<customername>Nova Systems</customername>
		<orderdate>10-april-2001</orderdate>
		<salesperson>Jack Nicholson</salesperson>
		<shippingaddress>12,green park</shippingaddress>
	</order>
	<order>
		<orderid>2</orderid>
		<customername>Iflex Systems</customername>
		<orderdate>20-april-2001</orderdate>
		<salesperson>Bill Gates</salesperson>
		<shippingaddress> M.G.Road </shippingaddress>
	</order>
</orders>
