=== srivastavatilotama1/VaishaliData/My IGate Web Basics/My Demo Web Basic/XML-Lect Demo/Example JAXB/JaxB/marshalling/JaxBPP/company.xsd
<schema targetNamespace="http://www.example.com/kogent"
	elementFormDefault="qualified" xmlns="http://www.w3.org/2001/XMLSchema"
	xmlns:kogent="http://www.example.com/kogent">
	<element name="Company">
		<complexType>
			<sequence>
				<element name="CompanyAddress">
					<complexType>
						<sequence>
							<element name="name" type="string" />
							<element name="street" type="string" />
							<element name="city" type="string" />
							<element name="state" type="string" />
							<element name="zipcode" type="string" />
							<element name="phnum" type="string" />
						</sequence>
					</complexType>
				</element>
				<element name="departments">
					<complexType>
						<sequence>
							<element name="department" type="kogent:DeptType"
								maxOccurs="unbounded" />
						</sequence>
					</complexType>
				</element>
			</sequence>
		</complexType>
	</element>
	<complexType name="DeptType">
		<sequence>
			<element name="deptmanager" type="string" />
			<element name="cost" type="double" />
		</sequence>
		<attribute name="deptname" use="required" type="string" />
	</complexType>
</schema>

=== srivastavatilotama1/VaishaliData/My IGate Web Basics/My Demo Web Basic/XML-Lect Demo/Example JAXB/JaxB/marshalling/JaxBPP/company.xml
<?xml version="1.0" encoding="UTF-8"?>
<kogent:Company xmlns:kogent="http://www.example.com/kogent" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.com/kogent company.xsd ">
  <kogent:CompanyAddress>
    <kogent:name>kogent:name</kogent:name>
    <kogent:street>kogent:street</kogent:street>
    <kogent:city>kogent:city</kogent:city>
    <kogent:state>kogent:state</kogent:state>
    <kogent:zipcode>kogent:zipcode</kogent:zipcode>
    <kogent:phnum>kogent:phnum</kogent:phnum>
  </kogent:CompanyAddress>
  <kogent:departments>
    <kogent:department deptname="computer">
      <kogent:deptmanager>kogent:deptmanager</kogent:deptmanager>
      <kogent:cost>0.0</kogent:cost>
    </kogent:department>
    
     <kogent:department deptname="IT">
      <kogent:deptmanager>kogent:deptmanager</kogent:deptmanager>
      <kogent:cost>0.0</kogent:cost>
    </kogent:department>
  </kogent:departments>
  
</kogent:Company>
