=== srivastavatilotama1/VaishaliData/My IGate Web Basics/My Demo Web Basic/XML-Lect Demo/Examples With DTDS/001-Employee/Complete-Emp-DTD/emp.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ENTITY copyright "Vaishali Srivastava">
<!ENTITY % address "(city, state)">
<!NOTATION filePath SYSTEM "C:\IBM Folder\XMLP\src\ibmDesc.txt">
<!ELEMENT employees (author,employee+)>
<!ELEMENT employee (ename,esal,eaddress)>
<!ELEMENT eaddress  %address;>
<!ELEMENT author (#PCDATA)>
<!ELEMENT city (#PCDATA)>
<!ELEMENT state (#PCDATA)>
<!ELEMENT esal (#PCDATA)>
<!ELEMENT ename ((fname,mname,lname)|(fname,lname)|(fname,mname))>
<!ATTLIST employee gender CDATA #REQUIRED>
<!ATTLIST esal currency CDATA #FIXED "RS">
<!ELEMENT fname (#PCDATA)>
<!ELEMENT mname (#PCDATA)>
<!ELEMENT lname (#PCDATA)>
<!ATTLIST fname title (MRS|MR) #IMPLIED>
<!ATTLIST employee emp_id ID #REQUIRED>
<!ATTLIST employee supervisor IDREF #IMPLIED>
<!ATTLIST employee compdesc NOTATION (filePath) #IMPLIED>

=== srivastavatilotama1/VaishaliData/My IGate Web Basics/My Demo Web Basic/XML-Lect Demo/Examples With DTDS/001-Employee/Complete-Emp-DTD/emp.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE employees SYSTEM "emp.dtd" >
<employees>
<author>&copyright;</author>
	<employee  compdesc="filePath" emp_id="E111" gender="M" supervisor="E112">
		<ename>
			<fname >Vaishali</fname>
			<mname>A</mname>			
		</ename>
		<esal>10000</esal>
		<eaddress>
			<city>pune</city>
			<state>maharashtra</state>		
		</eaddress>
	</employee>
	<employee  emp_id="E112" gender="F" >
		<ename>
			<fname title="MR">amit</fname>
			<mname>H</mname>
			<lname>Chaudhary</lname>
		</ename>
		<esal currency="RS">20000</esal>
		<eaddress>
			<city>pune</city>
			<state>maharashtra</state>		
		</eaddress>
	</employee>

</employees>
