=== srivastavatilotama1/VaishaliData/My IGate Web Basics/My Demo Web Basic/XML-Lect Demo/Examples With XSD/Complete-XSD/001-Simple Complet XSD/emp.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	
	<xs:simpleType name="phonePat">
		<xs:restriction base="xs:string">
			<xs:length value="15"/>
			<xs:pattern value="\d{4}-\d{4}-\d{5}"/>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="ageLimit">
		<xs:restriction base="xs:positiveInteger">
			<xs:maxInclusive value="100"/>
			<xs:minInclusive value="1"/>
		</xs:restriction>
	</xs:simpleType>

<xs:simpleType name="salVal">
		<xs:restriction base="xs:string">
			<xs:enumeration value="RS"/>
			<xs:enumeration value="R"/>
		</xs:restriction>
	</xs:simpleType>
	
<xs:element name="employees">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="employee" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
<xs:element name="employee">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="employeeName"/>
				<xs:element ref="empPhone"/>
				<xs:element ref="age"/>
				<xs:element ref="salary"/>			
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name="employeeName">
							<xs:complexType>	
									<xs:sequence>
											<xs:element name="fname" type="xs:string"/>
													<xs:element name="mname" type="xs:string"/>
													<xs:element name="lname" type="xs:string"/>
									</xs:sequence>
						</xs:complexType>
	</xs:element>
	
<xs:element name="empPhone" type="phonePat"/>

<xs:element name="age" type="ageLimit"/>

<xs:element name="salary">
		<xs:complexType>
				<xs:simpleContent>
						<xs:extension base="xs:integer">
									<xs:attribute name="currency" type="salVal"/>
							</xs:extension>
					    </xs:simpleContent>
	       	</xs:complexType>
</xs:element>

</xs:schema>

=== srivastavatilotama1/VaishaliData/My IGate Web Basics/My Demo Web Basic/XML-Lect Demo/Examples With XSD/Complete-XSD/002-Ref-Complete XSD/emp-1.xml
<?xml version="1.0" encoding="UTF-8"?><employees xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C:\VaishaliTemp\WiproXml\XSD Demo\emp.xsd"><employee>			<employeeName>						<fname>Vaishali</fname>						<mname>A</mname>						<lname>Srivastava</lname>			</employeeName>			<empPhone>5576-5565-77477</empPhone>			<age>30</age>			<salary currency="RS">40000</salary></employee>	<employee>			<employeeName>						<fname>Nidhi</fname>						<mname>B</mname>						<lname>Sharma</lname>			</employeeName>			<empPhone>1111-1111-11111</empPhone>			<age>23</age>			<salary currency="RS">20000</salary></employee>			</employees>
