=== srivastavatilotama1/VaishaliData/My IGate Web Basics/My Demo Web Basic/XML-Lect Demo/Example JAXB/Cars.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema elementFormDefault="qualified"
	xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://www.ociweb.com/cars"
	targetNamespace="http://www.ociweb.com/cars">
	<xs:complexType name="car">
		<xs:sequence>
			<xs:element name="make" type="xs:string" />
			<xs:element name="model" type="xs:string" />
			<xs:element name="color" type="xs:string" />
		</xs:sequence>
		<xs:attribute name="year" type="xs:positiveInteger" use="required" />
	</xs:complexType>
	<xs:element name="cars">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="car" type="car" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== srivastavatilotama1/VaishaliData/My IGate Web Basics/My Demo Web Basic/XML-Lect Demo/Example JAXB/Cars.xml
<?xml version="1.0" encoding="UTF-8"?>
<cars xmlns="http://www.ociweb.com/cars" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.ociweb.com/cars Cars.xsd ">
	<car year="2001">
		<make>BMW</make>
		<model>Z3</model>
		<color>yellow</color>
	</car>
	<car year="2001">
		<make>Honda</make>
		<model>Odyssey</model>
		<color>green</color>
	</car>
	<car year="1997">
		<make>Saturn</make>
		<model>SC2</model>
		<color>purple</color>
	</car>
</cars>
