=== srivastavatilotama1/VaishaliData/My IGate Web Basics/My Demo Web Basic/XML-Lect Demo/Examples With XSD/021-ComplexContents/policeman.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.person.org/policeman"
	xmlns:tns="http://www.person.org/policeman" elementFormDefault="qualified">

	<element name="house" type="tns:House" />
	<element name="policeman" type="tns:Policeman" />
	<element name="doctor" type="tns:Doctor" />

	<complexType name="Person" abstract="true">
		<sequence>
			<element name="firstname" nillable="false" type="string" />
			<element name="lastname" type="string" nillable="false" />
			<element name="age" type="integer" />
		</sequence>
	</complexType>

	<complexType name="Policeman">
		<complexContent>
			<extension base="tns:Person">
				<sequence>
					<element name="precinct" type="string" />
					<element name="precintCode" type="string" />
					<element name="cation" type="string" minOccurs="0" />
				</sequence>
			</extension>
		</complexContent>
	</complexType>

	<complexType name="Doctor">
		<complexContent>
			<extension base="tns:Person">
				<sequence>
					<element name="speciality" type="string" />
				</sequence>
			</extension>
		</complexContent>
	</complexType>

	<complexType name="Persons">
		<sequence>
			<element name="person" type="tns:Person" minOccurs="0"		maxOccurs="unbounded">
			</element>
		</sequence>
	</complexType>

	<complexType name="House">
		<all>
			<element name="street" type="string" />
			<element name="city" type="string" />
			<element name="inhabitant" type="tns:Persons" />
		</all>
	</complexType>


</schema>

=== srivastavatilotama1/VaishaliData/My IGate Web Basics/My Demo Web Basic/XML-Lect Demo/Examples With XSD/021-ComplexContents/pp.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:house xmlns:tns="http://www.person.org/policeman"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.person.org/policeman policeman.xsd ">
	<tns:street>tns:street</tns:street>
	<tns:city>tns:city</tns:city>
	<tns:inhabitant>
		<tns:person xsi:type="tns:Policeman">
			<tns:firstname>bbb</tns:firstname>
			<tns:lastname>bbb</tns:lastname>
			<tns:age>33</tns:age>
			<tns:precinct>ddd</tns:precinct>
			<tns:precintCode>fff</tns:precintCode>
			<tns:cation>fff</tns:cation>
		</tns:person>
		<tns:person xsi:type="tns:Doctor">
			<tns:firstname>vv</tns:firstname>
			<tns:lastname>nn</tns:lastname>
			<tns:age>22</tns:age>
			<tns:speciality>ddd</tns:speciality>
		</tns:person>
	</tns:inhabitant>
</tns:house>
